from django.urls import path

from trading_bot.bot.views import (
    agent_approve_view,
    agent_health_view,
    agent_logs_view,
    agent_portfolio_view,
    agent_proposals_view,
    agent_reject_view,
    agent_session_view,
    agent_start_view,
    agent_stop_view,
    best_candidates_view,
    best_projection_view,
    candle_playground_view,
    crypto_agent_approve_view,
    crypto_agent_logs_view,
    crypto_agent_proposals_view,
    crypto_agent_reject_view,
    crypto_agent_session_view,
    crypto_agent_start_view,
    crypto_agent_stop_view,
    dashboard_view,
    market_monitor_view,
    trading_suggestion_view,
)

urlpatterns = [
    path("", dashboard_view, name="dashboard"),
    path("api/suggestion/", trading_suggestion_view, name="trading-suggestion"),
    path("api/candidates/", best_candidates_view, name="best-candidates"),
    path("api/projections/", best_projection_view, name="best-projection"),
    path("api/market-monitor/", market_monitor_view, name="market-monitor"),
    path("api/playground/", candle_playground_view, name="candle-playground"),
    path("api/agent/start", agent_start_view, name="agent-start"),
    path("api/agent/stop", agent_stop_view, name="agent-stop"),
    path("api/agent/session", agent_session_view, name="agent-session"),
    path("api/agent/logs", agent_logs_view, name="agent-logs"),
    path("api/agent/proposals", agent_proposals_view, name="agent-proposals"),
    path("api/agent/proposals/<str:proposal_id>/approve", agent_approve_view, name="agent-approve"),
    path("api/agent/proposals/<str:proposal_id>/reject", agent_reject_view, name="agent-reject"),
    path("api/agent/portfolio", agent_portfolio_view, name="agent-portfolio"),
    path("api/agent/health", agent_health_view, name="agent-health"),
    path("api/agent-crypto/start", crypto_agent_start_view, name="crypto-agent-start"),
    path("api/agent-crypto/stop", crypto_agent_stop_view, name="crypto-agent-stop"),
    path("api/agent-crypto/session", crypto_agent_session_view, name="crypto-agent-session"),
    path("api/agent-crypto/logs", crypto_agent_logs_view, name="crypto-agent-logs"),
    path("api/agent-crypto/proposals", crypto_agent_proposals_view, name="crypto-agent-proposals"),
    path(
        "api/agent-crypto/proposals/<str:proposal_id>/approve",
        crypto_agent_approve_view,
        name="crypto-agent-approve",
    ),
    path(
        "api/agent-crypto/proposals/<str:proposal_id>/reject",
        crypto_agent_reject_view,
        name="crypto-agent-reject",
    ),
]
