# Generated by Django 5.2.12 on 2026-04-02 20:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposal_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("symbol", models.CharField(max_length=16)),
                ("action", models.CharField(max_length=32)),
                ("size", models.FloatField(default=0.0)),
                ("rationale", models.TextField()),
                ("risk_summary", models.TextField()),
                ("explanation", models.TextField()),
                ("confidence", models.FloatField(default=0.0)),
                ("expected_impact", models.TextField()),
                ("why_now", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("status", models.CharField(default="drafted", max_length=24)),
                ("snapshot_hash", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("status", models.CharField(max_length=32)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("latest_sync_at", models.DateTimeField(blank=True, null=True)),
                ("latest_analysis_at", models.DateTimeField(blank=True, null=True)),
                ("worker_healthy", models.BooleanField(default=False)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField()),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="bot.agentproposal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agentproposal",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="bot.agentsession",
            ),
        ),
        migrations.CreateModel(
            name="AgentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(max_length=16)),
                ("category", models.CharField(max_length=32)),
                ("symbol", models.CharField(blank=True, max_length=16)),
                ("message", models.TextField()),
                ("payload", models.JSONField(default=dict)),
                ("ui_line", models.TextField(default="")),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bot.agentproposal",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="bot.agentsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExecutionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=24)),
                ("payload", models.JSONField(default=dict)),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bot.agentproposal",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_events",
                        to="bot.agentsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("account_summary", models.JSONField(default=dict)),
                ("positions", models.JSONField(default=list)),
                ("open_orders", models.JSONField(default=list)),
                ("portfolio_history", models.JSONField(default=list)),
                ("snapshot_hash", models.CharField(max_length=128)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="bot.agentsession",
                    ),
                ),
            ],
        ),
    ]
