# Generated by Django 5.2.12 on 2026-04-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_agent_signal_expansion"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentproposal",
            name="attention_summary",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="agentsession",
            name="market",
            field=models.CharField(default="trader", max_length=16),
        ),
    ]
